### ISSUE TITLE
Instagraph missing from OpenStore

### ISSUE THREAD

**Issue by vagrale13** [turanmahmudov/Instagraph#23] opened 2017-09-19 11:53 UTC
I'm trying to install Instagraph but i don't find it in OpenStore. 
Device: BQ Aquaris E4.5 Ubuntu

**Comment by nfsprodriver** [comment] 2017-10-29 00:44
Duplicate of #15 , now it's already in the OpenStore. Thanks!
This issue can be closed...

**Closed** 2017-11-05 16:44 UTC
