### ISSUE TITLE
Sorry, there aren't currently any apps installed that can provide this type of content

### ISSUE THREAD

**Issue by oix** [turanmahmudov/Instagraph#22] opened 2017-09-08 08:37 UTC
Hello everyone

When trying to post a picture, or clicking on the (download ?) icon (the arrow), I have this message :

> Sorry, there aren't currently any apps installed that can provide this type of content

Is it about to connect something ?  Or is there any thing else ?

Thank you

**Comment by turanmahmudov** [comment] 2017-09-10 17:03
Hello @oix 
Which device do you use? 
The app uses content-hub to select or download photos.

**Comment by oix** [comment] 2017-09-21 22:08
Hello

Thank you for your answer

I'm actually using Ubuntu 17.04 64 with Gnome Shell 3.24.2 (on a Lenovo
B50-70 Laptop)

Hope to hear from you soon :)

Regards

____________________________________________________

2017-09-10 18:03 GMT+01:00 Turan Mahmudov <notifications@github.com>:

**Comment by turanmahmudov** [comment] 2017-11-05 16:52
Duplicate of #24

**Closed by turanmahmudov** 2017-11-05 16:52 UTC
Labels: bug, help wanted
