### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by juusechec** [turanmahmudov/Instagraph#45] opened 2018-06-12 16:05 UTC
I've installed with
```
snap install instagraph
snap connect instagraph:camera :camera
snap connect instagraph:alsa :alsa
snap connect instagraph:pulseaudio :pulseaudio
snap connect instagraph:opengl :opengl
```
But when I want to execute, appear the error:
```
/snap/instagraph/70/bin/instagraph: line 13: /snap/instagraph/70/opt/Instagraph/bin/Instagraph: No such file or directory
```

**Comment by turanmahmudov** [comment] 2018-07-01 12:49
Duplicate of #43 
Working on to fix it.

**Closed by turanmahmudov** 2018-07-01 12:49 UTC
